export const POSTING_ERROR_CODES = [
    'FORM_INVALID',
    'AUTH_REQUIRED',
    'AUTH_CHECK_FAILED',
    'MEMBERSHIP_REQUIRED',
    'MEMBERSHIP_CHECK_FAILED',
    'PHOTO_COUNT_INVALID',
    'POSTING_SETUP_REQUIRED',
    'POSTING_PERMISSION_DENIED',
    'LISTING_DETAILS_REJECTED',
    'LISTING_CREATE_CONFLICT',
    'LISTING_CREATE_UNAVAILABLE',
    'LISTING_UPDATE_LOCKED',
    'LISTING_UPDATE_UNAVAILABLE',
    'PHOTO_RESERVATION_FAILED',
    'LISTING_ID_INVALID',
    'DRAFT_LOOKUP_FAILED',
    'DRAFT_UNAVAILABLE',
    'DRAFT_CANCELLED',
    'PUBLISH_STATE_CONFLICT',
    'PHOTO_RESERVATIONS_MISSING',
    'PHOTO_RESERVATIONS_INVALID',
    'PHOTO_STORAGE_SETUP_REQUIRED',
    'PHOTO_STORAGE_CHECK_FAILED',
    'PHOTO_UPLOAD_INCOMPLETE',
    'PHOTO_UPLOAD_SET_INVALID',
    'PHOTO_VERIFY_READ_FAILED',
    'PHOTO_TYPE_UNSUPPORTED',
    'PHOTO_ORIGINAL_TOO_LARGE',
    'PHOTO_PROCESSING_UNSUPPORTED',
    'PHOTO_PROCESSING_FAILED',
    'PHOTO_OUTPUT_TOO_LARGE',
    'PHOTO_SLOT_MISMATCH',
    'UPLOAD_SESSION_EXPIRED',
    'UPLOAD_DRAFT_CLOSED',
    'PHOTO_UPLOAD_CONFLICT',
    'PHOTO_UPLOAD_RATE_LIMITED',
    'PHOTO_UPLOAD_UNAVAILABLE',
    'PHOTO_CORRUPT',
    'PHOTO_DIMENSIONS_TOO_LARGE',
    'PHOTO_PIXEL_COUNT_TOO_HIGH',
    'PUBLISH_UNAVAILABLE',
    'CLEANUP_ID_INVALID',
    'CLEANUP_AUTH_REQUIRED',
    'CLEANUP_LOOKUP_FAILED',
    'CLEANUP_BUSY',
    'CLEANUP_STATE_INVALID',
    'CLEANUP_STORAGE_FAILED',
    'CLEANUP_UNAVAILABLE',
    'CONNECTION_FAILED',
] as const

export type PostingErrorCode = (typeof POSTING_ERROR_CODES)[number]

export type PostingError = {
    code: PostingErrorCode
    message: string
    retryable: boolean
}

export function createPostingError(
    code: PostingErrorCode,
    message: string,
    retryable = false,
): PostingError {
    return { code, message, retryable }
}
